### ISSUE TITLE
Add missing details and examples

### ISSUE THREAD

**Issue by monkeyscript** [monkeyscript/website-perf-checklist#1]
Add explanations and examples for the points which lack clarity. Any additional metrics are also welcomed.

**Comment by arunNewPhoenix** [comment]
hey, @monkeyscript I am interested in doing this could you please assign it to me.!
you can too review my **linkedin profile. I am a participant of hacktoberfest..!**
#good_first_issue

**Comment by monkeyscript** [comment]
@arun2145 All valid contributions are welcomed.
